### ISSUE TITLE
Faster ffi calls for assignment operators?

### ISSUE THREAD

**Issue by benruijl** [jkarns275/f128#32]
Currently, the assignment operators `*=,/=,-=,+=` are implemented by making copies:
```
    fn add_assign(&mut self, other: f128) {
        *self = *self + other;
    }
 ```
 Can accelerator ffi methods be used for those instead or do they not exist?
 
 For example, can we add something like:
 ```
  void f128_addassign(Wrapper* a, Wrapper b){
    a.value += b.value;
}
```

**Comment by jkarns275** [comment]
So with this test program

```
union Wrapper {
    __float128 value;
    char test[16];
};

void test(Wrapper *x, Wrapper y) {
    x->value += y.value;
}

Wrapper test2(Wrapper x, Wrapper y) {
    Wrapper z = { .value = x.value + y.value };
    return z;
}
```

GCC 11.1 with -O3 spits out the following assembly:
```
test(Wrapper*, Wrapper):
        push    rbx
        mov     rbx, rdi
        sub     rsp, 16
        movdqa  xmm0, XMMWORD PTR [rdi]
        mov     QWORD PTR [rsp], rsi
        mov     QWORD PTR [rsp+8], rdx
        movdqa  xmm1, XMMWORD PTR [rsp]
        call    __addtf3
        movaps  XMMWORD PTR [rbx], xmm0
        add     rsp, 16
        pop     rbx
        ret
test2(Wrapper, Wrapper):
        sub     rsp, 40
        mov     QWORD PTR [rsp+16], rdx
        mov     QWORD PTR [rsp], rdi
        mov     QWORD PTR [rsp+8], rsi
        movdqa  xmm0, XMMWORD PTR [rsp]
        mov     QWORD PTR [rsp+24], rcx
        movdqa  xmm1, XMMWORD PTR [rsp+16]
        call    __addtf3
        movaps  XMMWORD PTR [rsp], xmm0
        mov     rax, QWORD PTR [rsp]
        mov     rdx, QWORD PTR [rsp+8]
        add     rsp, 40
        ret
```
which is basically the same thing. The key here being the fact that the function where the addition is actually performed is `__addtf3` which takes two `long long double` values and returns their sum. The assembly generated for both functions copies the result form the xmm0 register onto the stack which is the return value of `__addtf3`.

Since the arithmetic provided by `libquadmath` is all emulated, a copy of 16 bytes is going to be negligible compared to the time it takes to actually execute any arithmetic function anyways. If you're looking performance, quadruple precision floating point numbers are not the place to look unfortunately.

**Comment by jkarns275** [comment]
Closing this for the reasons above
