### ISSUE TITLE
Into methods don't work correctly

### ISSUE THREAD

**Issue by TheDan64** [jkarns275/f128#7]
```rust
fn main() {
    let a = f128::f128::parse("1.2").unwrap();
    let b: f128::f128 = 1.2f64.into();
    let c: f128::f128 = 1.2f32.into();
    let d: f128::f128 = 12.into();

    println!("{:?}, {:?}, {:?}, {:?}", a, b, c, d);
}
```

prints out:
`1.19999999999999999999999999999999996`, `5.75729229616694185702232133544373545e-4945`, `1.45171707075140335730369789469963045e-4954` & `5.43214355091875692521655285173400408e-4959` of which only the first looks correct

**Comment by jkarns275** [comment]
Looks like casting doesn't work for the gcc __f128 type. The unfortunate temp solution will have to be converting those numbers to strings and then parsing them as __f128. I will try to patch this quickly

**Comment by jkarns275** [comment]
So i changed the API a bit to align with them traits provided by the `num_traits` crate, so your example above would now be:

```rust
extern crate num_traits;
fn main() {
    let a = f128::f128::parse("1.2").unwrap();
    let b: f128::f128 = f128::from_i64(1.2).unwrap();
    let c: f128::f128 = f128::from_i32(1.2).unwrap();
    let d: f128::f128 = f128::from_u32(12).unwrap();

    println!("{:?}, {:?}, {:?}, {:?}", a, b, c, d);
}
```

I think adding `Into` implementations for primitives may be convenient but I'd rather stick to a safe-ish API (though I can't imagine why these conversions would ever fail).

**Comment by jkarns275** [comment]
Also, I've not published this to crates.io yet. I'll continue polishing this crate for the next few days before I publish.

**Comment by TheDan64** [comment]
> I think adding Into implementations for primitives may be convenient but I'd rather stick to a safe-ish API (though I can't imagine why these conversions would ever fail).

If there's any way to prove that conversions cannot fail, the `Into` approach would be much appreciated as it made the `new` method super flexible and reusable. (I also don't see how they could fail. A stringified number should always be parse-able if the parser is correct?) But if not, no worries

> Also, I've not published this to crates.io yet. I'll continue polishing this crate for the next few days before I publish.

Sounds good, looking forward to it! Thanks for fixing this!

**Comment by jkarns275** [comment]
I've been doing some testing with the C code, and it looks like casting from a primitive to __float128 works just fine, so there must have been an issue with the FFI. Not sure what the issue with the FFI is though, but as soon as I'll do I'll be able to add the `Into` implementations, since C casts don't fail (or do they?).

**Comment by TheDan64** [comment]
I don't think the C cast is working fine. I added this line to the end of the `x_to_f128` macro: `printf("val: %f -> %Lf, %Lf\n", a, d.value, (f128) a);\` and I see 
```
val: 1.200000 -> nan, nan
val: 2.300000 -> 0.000000, nan
```
with values `1.2f64` and `2.3f32`, respectively (I assume the gcc `__f128` float type is valid for the long double formatter, but maybe not)

**Comment by jkarns275** [comment]
`%Lf` is not the proper formatter for __float128, I believe you have to manually convert to a string using `quadmath_snprintf(char* buf, size_t size, const char* fmt, __f128 value)`.

I modified the x_to_f128 macro to print using
```
char buf[64]; \
quadmath_snprintf(buf, 64, "%.10Qg", (f128) a); \
printf("%s\n", buf); \
```
Does this work for you?

**Comment by TheDan64** [comment]
Ack, yeah that looks better

**Comment by TheDan64** [comment]
Ok, I got it working. I now get: `1.19999999999999999999999999999999996, 1.19999999999999995559107901499373838, 1.2000000476837158203125, 12`

I'm not 100% sure where exactly is the problem, because there's a lot of seemingly unnecessary unsafe manipulation going on. But I refactored the code to make `f128` `repr(C)` and use that rather than byte arrays directly in both the ffi and internal functions, which simplifies the code a lot too and along the way it got fixed. I can submit a PR later if you'd like. Even if you don't like those changes, maybe it'll give you an idea as to the source of the problem

**Comment by jkarns275** [comment]
Not sure what those numbers mean - are those all results from the same input?

And the byte arrays are just useful for constants since f128 literals are not supported yet.
I'm not sure what you mean by `repr(C)` - do you do something like:
```
#[repr(C)]
struct f128(u128);
```
If so this is just as "unsafe" as using the byte arrays, there may be a few less calls to transmute but in this case I don't really see it as an issue.
Also, if my memory serves me right the reason I used byte arrays was to prevent compilers from using SSE registers because there is no guarantee that both `libquadmath` and `rustc` will use those registers, and using a byte array will force the compiler to use the stack. This may lead to a decrease in performance though.

**Comment by TheDan64** [comment]
Yeah, with the same input I originally had.

What I did was:

```rust
#[repr(C)]
struct f128(pub(crate) [u8; 16]);
```

This way you can still represent the internals as bytes, but manipulation becomes less painful (no longer need `f128::from_arr` everywhere) when you define your ffi (and non ffi) functions like this:

```rust
    pub fn f128_add(x: f128, y: f128) -> f128;
```

It is indeed just as unsafe, but less boilerplatey I guess is what I meant to say since the repr C `f128` is guaranteed to be the same size as the byte array. You can also do most of your transmutes directly to `f128`, and so on

**Comment by jkarns275** [comment]
Oh I see! I can make that change, unless you've already done it. I'll likely accept a PR if you make one.

**Comment by jkarns275** [comment]
Oh and just to clarify, those outputs (`1.19999999999999999999999999999999996, 1.19999999999999995559107901499373838, 1.2000000476837158203125, 12`) are great - the different decimals are just a consequence of floating point numbers being imprecise. Additionally, since the only `to_string` fn right now prints the maximum number of decimals, this is what is expected. If there were a rounding `to_string` fn it would almost certainly round those numbers off to 1.2 unless 36 decimals were requested.

**Comment by TheDan64** [comment]
> Oh and just to clarify, those outputs (1.19999999999999999999999999999999996, 1.19999999999999995559107901499373838, 1.2000000476837158203125, 12) are great

I know! 😄 sorry for not being clearer!

> Oh I see! I can make that change, unless you've already done it. I'll likely accept a PR if you make one.

I'll rebase my changes later and send you a PR!

**Comment by jkarns275** [comment]
Okay, sounds good!
